### ISSUE TITLE
Error loading folder (Orientatie meldingen)

### ISSUE THREAD

**Issue by Avdmaat** [diethard2/b4udignl#1]
Hi,
On several folders (Orientatie meldingen) i get an error when using the button "Open folder...", see below:

2015-12-16T11:44:12	1	Traceback (most recent call last):
			  File "C:/Users/avmt/.qgis2/python/plugins\b4udignl2\B4UdigNLDialog.py", line 330, in on_openMsgButton_clicked
			    self._loadMsg()
			  File "C:/Users/avmt/.qgis2/python/plugins\b4udignl2\B4UdigNLDialog.py", line 490, in _loadMsg
			    l_doc = self._openMsg(unicode(self.__dir))
			  File "C:/Users/avmt/.qgis2/python/plugins\b4udignl2\B4UdigNLDialog.py", line 513, in _openMsg
			    l_doc = wv.Doc(p_path)
			  File "C:/Users/avmt/.qgis2/python/plugins\b4udignl2\wv.py", line 90, in __init__
			    self._parse_xml(xml_file)
			  File "C:/Users/avmt/.qgis2/python/plugins\b4udignl2\wv.py", line 132, in _parse_xml
			    topElement = xmlObj.Parse(xmlFile)
			  File "C:/Users/avmt/.qgis2/python/plugins\b4udignl2\xml2obj.py", line 125, in Parse
			    ParserStatus = Parser.Parse(xmldata, 1)
			  File "C:/Users/avmt/.qgis2/python/plugins\b4udignl2\xml2obj.py", line 106, in CharacterData
			    data = data.encode()
			UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 26: ordinal not in range(128)

**Comment by diethard2** [comment]
To be able to reproduce I will need the result provided. I will request to send the original zipped result to my email adress. I also need to know in which version of QGIS this occurs and which windows version.

**Comment by Avdmaat** [comment]
Goede morgen,

Hierbij een oriëntatiemelding die een fout geeft.
De foutmelding treedt op in versie 2.12.1, maar ook in voorgaande versies, o.a. 2.8 en 2.10.
Op Windows 7 – 64bit.

Ik stuur nog een e-mail met het 2e en 3e deel van de orientatiemelding.

Met vriendelijke groet,

A. (Albert) van de Maat
adviseur Ruimte & Milieu

Aveco de Bondt

Burgemeester van der Borchstraat 2
7451 CH Holten
Postbus 64
7450 AB Holten
T: (+31) (0)548 - 85 33 33

M: (+31) (0)6 - 20 61 99 81
E: avdmaat@avecodebondt.nl<mailto:avdmaat@avecodebondt.nl>
www.avecodebondt.nl<http://www.avecodebondt.nl/>
K.v.K.: 30169759

Van: Diethard Jansen [mailto:notifications@github.com]
Verzonden: maandag 21 december 2015 19:18
Aan: diethard2/b4udignl <b4udignl@noreply.github.com>
CC: Albert van de Maat <avdmaat@avecodebondt.nl>
Onderwerp: Re: [b4udignl] Error loading folder (Orientatie meldingen) (#1)


To be able to reproduce I will need the result provided. I will request to send the original zipped result to my email adress. I also need to know in which version of QGIS this occurs and which windows version.

—
Reply to this email directly or view it on GitHub<https://github.com/diethard2/b4udignl/issues/1#issuecomment-166380887>.

Disclaimer: De informatie verzonden met dit emailbericht is uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Afzender staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden email, noch voor tijdige ontvangst daarvan. Afzender attendeert erop dat de vertrouwelijkheid van informatie verzonden per email niet gewaarborgd is. The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorised to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. Sender is neither liable for the proper and complete transmission of the information contained in this communication nor for any delay in its receipt. Please note that the confidentiality of e-mail communication is not warranted.

**Comment by Avdmaat** [comment]
Hierbij het 2e en 3e deel van de melding.

Met vriendelijke groet,

A. (Albert) van de Maat
adviseur Ruimte & Milieu

Aveco de Bondt

Burgemeester van der Borchstraat 2
7451 CH Holten
Postbus 64
7450 AB Holten
T: (+31) (0)548 - 85 33 33

M: (+31) (0)6 - 20 61 99 81
E: avdmaat@avecodebondt.nl<mailto:avdmaat@avecodebondt.nl>
www.avecodebondt.nl<http://www.avecodebondt.nl/>
K.v.K.: 30169759

Van: Diethard Jansen [mailto:notifications@github.com]
Verzonden: maandag 21 december 2015 19:18
Aan: diethard2/b4udignl <b4udignl@noreply.github.com>
CC: Albert van de Maat <avdmaat@avecodebondt.nl>
Onderwerp: Re: [b4udignl] Error loading folder (Orientatie meldingen) (#1)


To be able to reproduce I will need the result provided. I will request to send the original zipped result to my email adress. I also need to know in which version of QGIS this occurs and which windows version.

—
Reply to this email directly or view it on GitHub<https://github.com/diethard2/b4udignl/issues/1#issuecomment-166380887>.

Disclaimer: De informatie verzonden met dit emailbericht is uitsluitend bestemd voor de geadresseerde. Gebruik van deze informatie door anderen dan de geadresseerde is verboden. Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking van deze informatie aan derden is niet toegestaan. Afzender staat niet in voor de juiste en volledige overbrenging van de inhoud van een verzonden email, noch voor tijdige ontvangst daarvan. Afzender attendeert erop dat de vertrouwelijkheid van informatie verzonden per email niet gewaarborgd is. The information contained in this communication is confidential and may be legally privileged. It is intended solely for the use of the individual or entity to whom it is addressed and others authorised to receive it. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. Sender is neither liable for the proper and complete transmission of the information contained in this communication nor for any delay in its receipt. Please note that the confidentiality of e-mail communication is not warranted.

**Comment by diethard2** [comment]
I received the result provided and was able to reproduce the problem. I soon found a solution and created and released a new version 1.4.2 that fixed this issue.
