### ISSUE TITLE
Klic won't load

### ISSUE THREAD

**Issue by hansengelman** [diethard2/b4udignl#13]
Hello
probably the dutch kadaster has changed the KLIC melding once more. Since last week the "KLIC viewer" gives an error: Multiple logs are attached.

Please provide a solution asap, thanks
[python KLIC messages.txt](https://github.com/diethard2/b4udignl/files/4305719/python.KLIC.messages.txt)
[Python error log.txt](https://github.com/diethard2/b4udignl/files/4305721/Python.error.log.txt)

**Comment by HarmenK** [comment]
got something similar... is it still not fixed? @diethard2

**Comment by diethard2** [comment]
Please upgrade to QGIS LTR version 3.10.9 (best for use in production and documentation available).
Old QGIS version uses previous python version, backporting takes too much effort for this plugin.
