### ISSUE TITLE
klic melding als vector

### ISSUE THREAD

**Issue by jhpoosthoek** [diethard2/b4udignl#2]
Ik lees dat de klic melding binnenkort ook als vector beschikbaar zal zijn: http://www.gismagazine.nl/wion-gaat-wijzigen/

Weet jij of dit al het geval is? Ben je van plan dit in te bouwen?

Groet, Jelmer

**Comment by diethard2** [comment]
De ontwikkeling van de klicviewer die ook vector kan ondersteunen loopt voorspoedig.
Sterker nog ik ga er voor zorgen dat deze zowel de oude als nieuwe klicmeldingen kan ondersteunen.
Zie ook #4

**Comment by jhpoosthoek** [comment]
Dank je wel @diethard2!
