### ISSUE TITLE
Qgis crash after loading 2nd KLIC_levering

### ISSUE THREAD

**Issue by HKoevoets** [diethard2/b4udignl#3]
Hi, 

Whenever I try to load a second KLIC into my project, Qgis crashes.
I can circumvent this by closing and opening my Qgis project in between loading KLICs.
Even though I found this workaround, I thought I should mention it.

Indien ik in mijn Qgis project een tweede KLIC_levering wil toevoegen crashed Qgis.
Als ik tussen het inlezen van KLIC-leveringen mijn Qgisproject verlaat en opnieuw open is er niks aan de hand.
Er is dus mee te werken maar ik meld het toch even.

Regards Hanneke

**Comment by diethard2** [comment]
Old issue on a version I do not support anymore.
Currently I am working on loading several klic_leveringen in latest version of klic viewer. I noticed this was not working correctly!
