### ISSUE TITLE
Plugin not available for QGis 3

### ISSUE THREAD

**Issue by pvandegeer** [diethard2/b4udignl#4]
Are there any plans to port this plugin to QGIS3.x?

**Comment by diethard2** [comment]
Yes, but later.
Right now I am improving the plugin so it can not only digest current Klic messages but also the new KlicWin messages that include vectors! 
I do this in LTR version 2.14 which probably will work also in version 2.18. 
When I am finished I will upgrade it to version 3.
I have allready parsed the new xmls and converted the xml to vector layers as you can see.
Still need to style the layers, make it robust etc.
Demo of current stage:
![status_klicviewer](https://user-images.githubusercontent.com/1836181/47443000-ba543a00-d7b3-11e8-9141-67abdf6eb792.JPG)

**Comment by AErkoc** [comment]
Beste Diethard2,

Ik lees dat Klic vieuwer niet geschikt is voor Qgis 3. Komt er nog een versie uit voor Qgis 3 ? 

Gr,

Ali

**Comment by diethard2** [comment]
Beste Ali,

Vandaag 2e pinksterdag, ben ik goed opgeschoten met de nieuwe geupgrade Klic Viewer voor QGIS 3.
Ik moet deze nog even goed testen en dan zal naar verwachting de klicviewer plugin op 12 juni uploaden naar de Plugin repository. Ik verwacht dat deze voor 15 juni wordt goedgekeurd en dan ook voor iedereen beschikbaar is om te downloaden vanuit de plugin manager in QGIS 3.

**Comment by AErkoc** [comment]
Beste Diethard2,

Dank voor je bericht ik wacht het af. 

Gr,

Ali

**Comment by bvdbos** [comment]
Dit werkt al enige tijd?

**Comment by diethard2** [comment]
plugin is beschikbaar voor QGIS 3
