### ISSUE TITLE
fout bij bericht sluiten

### ISSUE THREAD

**Issue by bvdbos** [diethard2/b4udignl#5]
Bericht sluiten geeft een foutmelding in QGIS 3.2.4 op Win-10 en v 2.1.2 van de plugin. Lagen worden wel verwijderd maar bericht sluit niet.

`Er is een fout opgetreden bij het uitvoeren van Python code: 

RuntimeError: wrapped C/C++ object of type QgsRasterLayer has been deleted 
Traceback (most recent call last):
  File "C:/Users/bas.BAS-WIN7/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\B4UdigNLDialog.py", line 520, in on_removeMsgButton_clicked
    l_doc.removeLayers()
  File "C:/Users/bas.BAS-WIN7/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv.py", line 550, in removeLayers
    i_layer.remove()
  File "C:/Users/bas.BAS-WIN7/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\b4udignl2\core\wv_objects.py", line 317, in remove
    iface.removeLayer(self)
  File "C:\Users\bas.BAS-WIN7\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2\ifaceqgis.py", line 201, in removeLayer
    project.removeMapLayer(lyr)
RuntimeError: wrapped C/C++ object of type QgsRasterLayer has been deleted

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.4.2-Madeira Madeira, 22034aa070 

Python pad:
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python
C:/Users/bas.BAS-WIN7/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/bas.BAS-WIN7/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.4\bin\python37.zip
C:\PROGRA~1\QGIS3~1.4\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib
C:\PROGRA~1\QGIS3~1.4\bin
C:\PROGRA~1\QGIS3~1.4\apps\Python37
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.4\apps\Python37\lib\site-packages\Pythonwin
C:/Users/bas.BAS-WIN7/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\bas.BAS-WIN7\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\b4udignl2
F:/project/07-0800/0720 H S/R024 Eindhoven`

**Comment by diethard2** [comment]
Voor het oplossen van deze fout heb ik de klic levering nodig.
graag klic levering opsturen naar diethard.jansen at gmail.com
Ik wil ook graag weten of er slechts 1 klic levering is geladen of meerdere klic leveringen.
Momenteel ben ik druk bezig om het probleem op te lossen van het niet kunnen verwijderen van een klicmelding wanneer er meerdere leveringen zijn geladen.

**Comment by diethard2** [comment]
In de nieuwe versie van KLIC viewer v.2.2.0 is het probleem opgelost doordat je daar slechts 1 KLIC- levering tegelijkertijd kunt openen. Uiteraard ga ik proberen om in een toekomstige versie weer meerdere KLIC leveringen tegelijkertijd te kunnen openen.
