### ISSUE TITLE
gegevens in tijdelijke lagen

### ISSUE THREAD

**Issue by bvdbos** [diethard2/b4udignl#6]
Wanneer in QGIS 3.4.2 een KLIC-melding wordt ingeladen worden veel gegevens in tijdelijke lagen geplaatst. Na opslaan van het project zijn deze dus verdwenen. Het zou prettig zijn om deze gegevens wel te (ont)houden.

**Comment by diethard2** [comment]
De klic melding wordt inderdaad nu opgeslagen in tijdelijke memory lagen.
Het grote voordeel is dat de klic levering snel wordt geladen!

Er is een plugin beschikbaar de Memory Layer Saver, die tijdelijke memory lagen opslaat.
Deze werkt goed in combinatie met de klic viewer plugin. Alleen zal na het herladen de klic viewer leeg zijn en zullen ook de links naar de meegeleverde documentatie niet beschikbaar zijn. 
Ik zal dit opnemen in de handleiding!

Op dit moment is er ook een knop [ Opslaan in Project ] die nu niet geactiveerd is.
Zodra ik die functionaliteit verwezenlijkt heb, zal die knop actief worden. Daarna zal er na het laden van een project ook Klic viewer plugin gevuld zijn met thema's en gekoppelde documenten.
Dit is echter nog wel een pittig onderdeel om te ontwikkelen!

**Comment by diethard2** [comment]
Informatie toegevoegd in Engelse en Nederlandse handleiding. Bij de volgende release van de Klic viewer plugin zal deze voor gebruikers beschikbaar zijn.

**Comment by bvdbos** [comment]
Werkt perfect, thanks voor de tip!
